In [5]:
#1.python program to add two matrices
x=[[1,1,1],
  [1,1,1],
  [1,1,1]]

y=[[1,1,1],
  [1,1,1],
  [1,1,1]]

res=[[0,0,0],
    [0,0,0],
    [0,0,0]]

for i in range(len(x)):
    for j in range(len(x[0])):
        res[i][j]=x[i][j]+y[i][j]

for x in res:
    print(x)


[2, 2, 2]
[2, 2, 2]
[2, 2, 2]


In [6]:
#2.python program to multiply two matrices
import numpy as np
x=[[1,1,1],
  [1,1,1],
  [1,1,1]]

y=[[1,1,1],
  [1,1,1],
  [1,1,1]]

res=[[0,0,0],
    [0,0,0],
    [0,0,0]]

res=np.dot(x,y)

for x in res:
    print(x)

[3 3 3]
[3 3 3]
[3 3 3]


In [8]:
#3.python program to transpose a matrix
x=[[1,2,3],
  [4,5,6],
  [7,8,9]]

res=[[0,0,0],
    [0,0,0],
    [0,0,0]]
for i in range(len(x)):
    for j in range(len(x[0])):
        res[j][i]=x[i][j]
        
for x in res:
    print(x)

[1, 4, 7]
[2, 5, 8]
[3, 6, 9]


In [13]:
#4.python program to sort words of a string in alphabetic order
string="Hi hello?in order"
res=string.lower().split()
res.sort()
print(''.join(res))

hello?inhiorder


In [14]:
#5.python program to remove punctations from a given word
pun="!=-_+-@#$%^&*{}()|:"
st=input("Enter string")
res=""
for char in st:
    if char not in pun:
        res=res+char

print(res)
        

Enter stringsairaj!
sairaj
